connections = {
    'Tunis': ['Ariana', 'Sukrah', 'Hammamet', 'Nabeul', 'Radès', 'La Marsa'],
    'Sidi Bouzid': ['Kasserine', 'Gafsa', 'Kairouan'],
    'Sfax': ['Mahdia', 'Gabès', 'Medenine'],
    'Sousse': ['Mahdia', 'Monastir', 'Msaken'],
    'Kairouan': ['Sidi Bouzid', 'Kasserine', 'Tunis'],
    'Métouia': ['Kebili', 'Gafsa', 'Medenine'],
    'Kebili': ['Métouia', 'Gafsa', 'Medenine', 'Gabès'],
    'Sukrah': ['Tunis', 'Ariana', 'Radès', 'La Marsa'],
    'Gabès': ['Sfax', 'Kebili', 'Medenine', 'Tataouine'],
    'Ariana': ['Tunis', 'Sukrah', 'La Marsa', 'Ben Arous'],
    'Gafsa': ['Sidi Bouzid', 'Kasserine', 'Métouia'],
    'Msaken': ['Sousse', 'Monastir', 'Mahdia', 'Djemmal'],
    'Medenine': ['Sfax', 'Kebili', 'Gabès', 'Tataouine'],
    'Béja': ['Jendouba', 'Bizerte', 'Tunis'],
    'Kasserine': ['Sidi Bouzid', 'Kairouan', 'Gafsa', 'Béja'],
    'Radès': ['Tunis', 'La Marsa', 'Ben Arous'],
    'Hammamet': ['Tunis', 'Sousse', 'Nabeul', 'Kairouan'],
    'Tataouine': ['Gabès', 'Medenine', 'Zarzis', 'Matmata'],
    'Monastir': ['Sousse', 'Mahdia', 'Msaken', 'Kairouan'],
    'La Marsa': ['Tunis', 'Ariana', 'Sukrah', 'Radès'],
    'Ben Arous': ['Tunis', 'Ariana', 'La Marsa', 'Radès'],
    'Sakiet ez Zit': ['Radès', 'Sousse', 'Hammamet', 'La Marsa'],
    'Zarzis': ['Gabès', 'Medenine', 'Tataouine', 'Midoun'],
    'Ben Gardane': ['Zarzis', 'Medenine', 'Tataouine', 'Matmata'],
    'Mahdia': ['Sousse', 'Monastir', 'Msaken', 'Sfax'],
    'Houmt Souk': ['Midoun', 'Zarzis', 'Medenine', 'Menzel Bourguiba'],
    'Fouchana': ['Tunis', 'Ben Arous', 'Radès', 'La Marsa'],
    'Le Kram': ['Tunis', 'La Marsa', 'Ariana', 'Radès'],
    'El Kef': ['Tunis', 'Kasserine', 'Gafsa', 'Béja'],
    'El Hamma': ['Gabès', 'Medenine', 'Zarzis', 'Tataouine'],
    'Nabeul': ['Hammamet', 'Tunis', 'Béja', 'Korba'],
    'Le Bardo': ['Tunis', 'La Marsa', 'Ariana', 'Sakiet ez Zit'],
    'Djemmal': ['Sousse', 'Monastir', 'Mahdia', 'Msaken'],
    'Korba': ['Nabeul', 'Menzel Temime', 'Hammamet', 'Zarzis'],
    'Menzel Temime': ['Nabeul', 'Korba', 'Monastir', 'Sousse'],
    'Ghardimaou': ['Jendouba', 'El Kef', 'Béja'],
    'Midoun': ['Houmt Souk', 'Zarzis', 'Medenine', 'Menzel Bourguiba'],
    'Menzel Bourguiba': ['Béja', 'Menzel Temime', 'Midoun', 'Ghardimaou'],
    'Manouba': ['Tunis', 'Ariana', 'Le Bardo', 'Kairouan']
}